import { Provider } from "@/components/ui/provider"

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props
  return (
    <html suppressHydrationWarning>
      <head>
        <title>Admin Sanity</title>
        <meta title="Admin Sanity" content="Testing Sanity"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon.ico" />
      </head>

      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}

// // import { CacheProvider } from '@chakra-ui/next-js';
// // import { ChakraProvider } from '@chakra-ui/react';
// // import { theme } from './theme';


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//       {children}
//       </body>
//     </html>
//   );
// }
